version: '3'

services:
  django:
    build: .
    env_file:
      - .env
    volumes:
      # Useful in order to not give in the container a lot of useless files that we already wanted to ignore in the dockerignore
    - ./my_project:/home/django/webapp/my_project
    - ./apps:/home/django/webapp/apps
    ports:
      - '8000:8000'
    command: ["./script/wait_for_postgres.sh"]
    depends_on:
      - db
  db:
    image: postgres:10.5-alpine
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
    - db:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
        interval: 3s
        timeout: 1s
        retries: 5
  redis:
    image: redis:5.0.1
    volumes:
    - redis:/data
    healthcheck:
      test: "redis-cli ping"
      interval: 3s
      timeout: 1s
      retries: 5

  volumes:
    db:
    redis:
